import { BeerHouse } from "./types";

export const MUNICH_CENTER: [number, number] = [48.1374, 11.5755];

export const BEER_HOUSES: BeerHouse[] = [
  {
    id: "hofbraeuhaus",
    name: "Hofbräuhaus München",
    description: "The world-famous beer hall, home of the Hofbräu since 1589.",
    lat: 48.1376,
    lng: 11.5800,
    address: "Platzl 9, 80331 München",
  },
  {
    id: "augustiner-keller",
    name: "Augustiner-Keller",
    description: "Historic beer garden with a huge chestnut-shaded courtyard, serving Augustiner from wooden kegs.",
    lat: 48.1435,
    lng: 11.5516,
    address: "Arnulfstraße 52, 80335 München",
  },
  {
    id: "loewenbraeukeller",
    name: "Löwenbräukeller",
    description: "Grand beer hall and beer garden near Stiglmaierplatz.",
    lat: 48.1479,
    lng: 11.5583,
    address: "Nymphenburger Str. 2, 80335 München",
  },
  {
    id: "paulaner-nockherberg",
    name: "Paulaner am Nockherberg",
    description: "Paulaner's home brewery restaurant with a terraced beer garden overlooking the city.",
    lat: 48.1216,
    lng: 11.5824,
    address: "Hochstraße 77, 81541 München",
  },
  {
    id: "augustiner-braeustuben",
    name: "Augustiner Bräustuben",
    description: "Down-to-earth brewery-adjacent tavern favored by locals, big portions and cheap beer.",
    lat: 48.1392,
    lng: 11.5456,
    address: "Landsberger Str. 19, 80339 München",
  },
  {
    id: "hirschgarten",
    name: "Hirschgarten",
    description: "One of the largest beer gardens in the world, set in a deer park.",
    lat: 48.1495,
    lng: 11.5110,
    address: "Hirschgarten 1, 80639 München",
  },
  {
    id: "chinesischer-turm",
    name: "Chinesischer Turm",
    description: "Iconic beer garden beneath a Chinese pagoda tower in the Englischer Garten.",
    lat: 48.1526,
    lng: 11.5921,
    address: "Englischer Garten 3, 80538 München",
  },
  {
    id: "viktualienmarkt",
    name: "Viktualienmarkt Biergarten",
    description: "Small, lively beer garden right in the middle of the famous food market.",
    lat: 48.1353,
    lng: 11.5764,
    address: "Viktualienmarkt 9, 80331 München",
  },
  {
    id: "andechser-am-dom",
    name: "Andechser am Dom",
    description: "Cozy tavern near the Frauenkirche pouring Andechs monastery beers.",
    lat: 48.1382,
    lng: 11.5738,
    address: "Frauenplatz 7, 80331 München",
  },
  {
    id: "schneider-braeuhaus",
    name: "Schneider Bräuhaus (Weisses Bräuhaus)",
    description: "The original home of Schneider Weisse wheat beer, near Marienplatz.",
    lat: 48.1364,
    lng: 11.5784,
    address: "Tal 7, 80331 München",
  },
  {
    id: "erdinger-weissbraeu",
    name: "Erdinger Weissbräu Festzelt",
    description: "Erdinger's own festival tent at Herbstfest Erding, the town's own answer to Oktoberfest.",
    lat: 48.3144,
    lng: 11.9126,
    address: "Am Stadion, 85435 Erding",
  },
  {
    id: "augustiner-am-dom",
    name: "Augustiner am Dom",
    description: "Cosy Augustiner tavern tucked right behind the Frauenkirche's towers.",
    lat: 48.1382,
    lng: 11.5740,
    address: "Frauenplatz 8, 80331 München",
  },
  {
    id: "airbraeu",
    name: "Airbräu",
    description: "The airport's own micro-brewery, in case the crawl needs to start (or end) at the gate.",
    lat: 48.3542,
    lng: 11.7877,
    address: "Nordallee 3, 85356 München-Flughafen",
  },
  {
    id: "seehaus",
    name: "Seehaus im Englischer Garten",
    description: "Lakeside beer garden on the Kleinhesseloher See, popular for a sunny afternoon by the water.",
    lat: 48.1605,
    lng: 11.5982,
    address: "Kleinhesselohe 3, 80802 München",
  },
  {
    id: "aumeister",
    name: "Aumeister",
    description: "Quiet beer garden tucked at the northern end of the Englischer Garten, away from the crowds.",
    lat: 48.1856,
    lng: 11.6204,
    address: "Sondermeierstraße 1, 80805 München",
  },
  {
    id: "hirschau",
    name: "Hirschau",
    description: "Big, family-friendly beer garden in the Englischer Garten near the Aumeister trail.",
    lat: 48.1621,
    lng: 11.6025,
    address: "Gyßlingstraße 15, 80805 München",
  },
];
