import { BeerHouse } from "./types";

export const MUNICH_CENTER: [number, number] = [48.1374, 11.5755];

export const BEER_HOUSES: BeerHouse[] = [
  {
    id: "hofbraeuhaus",
    name: "Hofbräuhaus München",
    description: "The world-famous beer hall, home of the Hofbräu since 1589.",
    lat: 48.1374,
    lng: 11.5799,
    address: "Platzl 9, 80331 München",
  },
  {
    id: "augustiner-keller",
    name: "Augustiner-Keller",
    description: "Historic beer garden with a huge chestnut-shaded courtyard, serving Augustiner from wooden kegs.",
    lat: 48.1447,
    lng: 11.5525,
    address: "Arnulfstraße 52, 80335 München",
  },
  {
    id: "loewenbraeukeller",
    name: "Löwenbräukeller",
    description: "Grand beer hall and beer garden near Stiglmaierplatz.",
    lat: 48.1462,
    lng: 11.5580,
    address: "Nymphenburger Str. 2, 80335 München",
  },
  {
    id: "paulaner-nockherberg",
    name: "Paulaner am Nockherberg",
    description: "Paulaner's home brewery restaurant with a terraced beer garden overlooking the city.",
    lat: 48.1195,
    lng: 11.5836,
    address: "Hochstraße 77, 81541 München",
  },
  {
    id: "augustiner-braeustuben",
    name: "Augustiner Bräustuben",
    description: "Down-to-earth brewery-adjacent tavern favored by locals, big portions and cheap beer.",
    lat: 48.1327,
    lng: 11.5433,
    address: "Landsberger Str. 19, 80339 München",
  },
  {
    id: "hirschgarten",
    name: "Hirschgarten",
    description: "One of the largest beer gardens in the world, set in a deer park.",
    lat: 48.1483,
    lng: 11.5119,
    address: "Hirschgarten 1, 80639 München",
  },
  {
    id: "chinesischer-turm",
    name: "Chinesischer Turm",
    description: "Iconic beer garden beneath a Chinese pagoda tower in the Englischer Garten.",
    lat: 48.1600,
    lng: 11.5952,
    address: "Englischer Garten 3, 80538 München",
  },
  {
    id: "viktualienmarkt",
    name: "Viktualienmarkt Biergarten",
    description: "Small, lively beer garden right in the middle of the famous food market.",
    lat: 48.1351,
    lng: 11.5761,
    address: "Viktualienmarkt 9, 80331 München",
  },
  {
    id: "andechser-am-dom",
    name: "Andechser am Dom",
    description: "Cozy tavern near the Frauenkirche pouring Andechs monastery beers.",
    lat: 48.1382,
    lng: 11.5748,
    address: "Landschaftstraße 8, 80331 München",
  },
  {
    id: "schneider-braeuhaus",
    name: "Schneider Bräuhaus (Weisses Bräuhaus)",
    description: "The original home of Schneider Weisse wheat beer, near Marienplatz.",
    lat: 48.1362,
    lng: 11.5786,
    address: "Tal 7, 80331 München",
  },
  {
    id: "erdinger-weissbraeu",
    name: "Erdinger Weissbräu",
    description: "Home of Erdinger Weissbier, a short trip out to the brewery town of Erding.",
    lat: 48.3149,
    lng: 11.8967,
    address: "Franz-Brombach-Straße 2, 85435 Erding",
  },
];
